server {
    listen 80;
    index index.php index.html;
    server_name _;
    root /var/www/html/public;

    location ^~ /livewire {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Servir archivos estáticos SIN pasar a PHP
    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|json)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
        add_header Access-Control-Allow-Origin "*";
        access_log off;
        log_not_found off;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
    location /storage {
        alias /var/www/html/storage/app/public;
        access_log off;
        expires max;
        add_header Cache-Control public;
    }
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}